spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/FleetPulse}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ingestion-service
          uri: lb://INGESTION-SERVICE
          predicates:
            - Path=/api/v1/ingest/**
        - id: fleet-management-service
          uri: lb://FLEET-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/fleet/**, /api/v1/vehicles/**
        - id: alert-service
          uri: lb://ALERT-SERVICE
          predicates:
            - Path=/api/v1/alerts/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

server:
  port: 8060
